setup.sh: Restrict the python file link to python2 [V2] [ LIN1019-3837 ]
Issue: LIN1019-3837

If /usr/bin/python links to python3, when use parameters --user and
--password for user and password of the product git repository,
there will be fail message.

Fetching buildtools..
Traceback (most recent call last):
  File "/home/wrsadmin/disk/project/wr1019/windshare_w9/data/environment.d/setup_askpass", line 121, in <module>
    s.send('q' + sys.argv[1])
TypeError: a bytes-like object is required, not 'str'
error: unable to read askpass response from '/home/wrsadmin/disk/project/wr1019/windshare_w9/data/environment.d/setup_askpass'

This is because the setup_askpass was written with python2, so require
the link file of /usr/bin/python to be python2.

Signed-off-by: De Huo <De.Huo@windriver.com>