bin/setup.py: Use relative symlink for buildtools
Issue: LINCD-1485

All the other symlinks in the top project dir use relative paths, so also make
this one use relative symlink.

This can also fix a fatal error when the project is moved to other dirs:
FileExistsError: [Errno 17] File exists: '/path/to/environment-setup-x86_64-wrlinuxsdk-linux' -> 'environment-setup-x86_64-wrlinuxsdk-linux'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>