setup.sh: Hide error messages, and check for SSL support in urllib
Issue: LIN1019-70

The setup tool can check for basic system capabilities, but apparently a
few instances of python3 without SSL support have been detected.  This causes
a failure that looks like:

ERROR: Traceback (most recent call last):
ERROR:   File "/.../wrlinux-x/bin/setup.py", line 1245, in <module>
ERROR:
ERROR: x.main(sys.argv)
ERROR:   File "/.../wrlinux-x/bin/setup.py", line 174, in main
ERROR:
ERROR: self.load_layer_index()
ERROR:   File "/.../wrlinux-x/bin/setup.py", line 364, in load_layer_index
ERROR:
ERROR: self.index = Layer_Index(indexcfg=settings.INDEXES, base_branch=self.base_branch, replace=replace, mirror=mirror_index_path)
ERROR:   File "/.../wrlinux-x/bin/layer_index.py", line 109, in __init__
ERROR:
ERROR: lindex = self.load_API_Index(indexurl, indexname, branches=branch)
ERROR:   File "/.../wrlinux-x/bin/layer_index.py", line 201, in load_API_Index
ERROR:
ERROR: lindex['apilinks'] = _get_json_response(url)
ERROR:   File "/.../wrlinux-x/bin/layer_index.py", line 183, in _get_json_response
ERROR:
ERROR: res = utils_setup.fetch_url(apiurl)
ERROR:   File "/.../wrlinux-x/bin/utils_setup.py", line 144, in fetch_url
ERROR:
ERROR: opener = urllib.request.build_opener(urllib.request.HTTPSHandler(debuglevel=debuglevel))
ERROR: AttributeError
ERROR: :
ERROR: module 'urllib.request' has no attribute 'HTTPSHandler'

Signed-off-by: Mark Hatle <mark.hatle@windriver.com>