07_toaster_update.sh:  Call toaster_fixture.py on when default.xml exists
The default.xml is only created on an install.  If the user runs:
  .../wrlinux-9/setup.sh --list-machines

The will recieve an error:
  ERROR: 'default.xml' does not exist. You need to run the 'setup' program.

So we simply check for the existence of the file before calling the toaster
fixture app.

Signed-off-by: Mark Hatle <mark.hatle@windriver.com>