bin/setup.py: Fix for BBFILE_COLLECTIONS is None
Issue: LINCD-3271

Fixed when a layer's BBFILE_COLLECTIONS is not defined:
ERROR: lines.append("PNWHITELIST_LAYERS = '%s'" % ' '.join(sorted(collections)))
ERROR: TypeError
ERROR: :
ERROR: '<' not supported between instances of 'NoneType' and 'str'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>