04_wrl_buildtools.sh: Update to buildtools-standalone-10.20.04.0
Issue: LINCD-883

To include nativesdk-python3-jinja2 which is required by ptest:

File "/path/to/layers/oe-core/scripts/lib/resulttool/report.py", line 162, in print_test_report
from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>